services:
  api:
    volumes:
      - ./services/api:/var/www/html
      - storage_data:/var/www/html/storage
    environment:
      APP_ENV: local
      APP_DEBUG: "true"
      MAIL_MAILER: smtp
      MAIL_HOST: mailpit
      MAIL_PORT: "1025"
      MAIL_ENCRYPTION: "null"

  queue:
    volumes:
      - ./services/api:/var/www/html
      - storage_data:/var/www/html/storage

  web:
    volumes:
      - ./services/web:/app
      - /app/node_modules
      - /app/.next
    command: npm run dev

  mysql:
    ports:
      - "3306:3306"

  mongodb:
    ports:
      - "27017:27017"

  redis:
    ports:
      - "6379:6379"

  mailpit:
    image: axllent/mailpit:latest
    ports:
      - "8025:8025"
      - "1025:1025"
    networks:
      - vendora-backend
