// Yoast-style XSLT stylesheet for the XML sitemaps. Referenced from each
// sitemap via <?xml-stylesheet?>. Search engines ignore it and read the raw
// XML; browsers apply it and render a styled, clickable table. Served as a
// route handler so the Content-Type is a reliable text/xsl (a public/*.xsl
// static file can be mislabelled application/octet-stream and won't apply).
export const revalidate = false

const XSL = `<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="1.0"
  xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
  xmlns:s="http://www.sitemaps.org/schemas/sitemap/0.9"
  xmlns:image="http://www.google.com/schemas/sitemap-image/1.1"
  xmlns:xhtml="http://www.w3.org/1999/xhtml">
  <xsl:output method="html" version="1.0" encoding="UTF-8" indent="yes"/>
  <xsl:template match="/">
    <html lang="en">
      <head>
        <meta charset="utf-8"/>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <meta name="robots" content="noindex,follow"/>
        <title>XML Sitemap &#8212; Yerevan Digital</title>
        <style>
          :root{color-scheme:light;--bg:#f8fafc;--card:#ffffff;--fg:#0f172a;--muted:#64748b;
                --border:#e2e8f0;--brand:#6863f5;--brand-soft:#eeecff;--row:#f8fafc;}
          *{box-sizing:border-box}
          body{margin:0;background:var(--bg);color:var(--fg);
               font:14px/1.6 -apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Helvetica,Arial,sans-serif;}
          .wrap{max-width:1100px;margin:0 auto;padding:32px 20px 64px}
          header{margin-bottom:24px}
          .brand{display:flex;align-items:center;gap:10px;font-weight:700;font-size:18px;margin-bottom:18px}
          .brand .dot{width:26px;height:26px;border-radius:7px;background:var(--brand);
                      display:inline-block;flex:none}
          h1{font-size:24px;margin:0 0 6px}
          .intro{color:var(--muted);margin:0;max-width:70ch}
          .intro a{color:var(--brand)}
          .count{margin:22px 0 12px;color:var(--muted)}
          .count strong{color:var(--fg)}
          .card{background:var(--card);border:1px solid var(--border);border-radius:12px;overflow:hidden}
          .scroll{overflow-x:auto}
          table{border-collapse:collapse;width:100%;font-size:13px}
          th,td{text-align:left;padding:11px 14px;border-bottom:1px solid var(--border);white-space:nowrap}
          th{background:var(--brand-soft);color:var(--fg);font-weight:600;
             text-transform:uppercase;letter-spacing:.04em;font-size:11px}
          td.url{white-space:normal;word-break:break-all}
          tr:last-child td{border-bottom:0}
          tbody tr:nth-child(even){background:var(--row)}
          td a{color:var(--brand);text-decoration:none}
          td a:hover{text-decoration:underline}
          .num{color:var(--muted);text-align:right;font-variant-numeric:tabular-nums}
          footer{margin-top:24px;color:var(--muted);font-size:12px}
        </style>
      </head>
      <body>
        <div class="wrap">
          <header>
            <div class="brand"><span class="dot"></span> Yerevan Digital</div>
            <h1>XML Sitemap</h1>
            <p class="intro">This is an XML Sitemap, meant for consumption by search engines.
              You can find more information about XML sitemaps on
              <a href="https://www.sitemaps.org/">sitemaps.org</a>.</p>
          </header>
          <xsl:apply-templates/>
          <footer>Generated by Yerevan Digital.</footer>
        </div>
      </body>
    </html>
  </xsl:template>

  <!-- Sitemap index: a list of child sitemaps -->
  <xsl:template match="s:sitemapindex">
    <p class="count">This index references
      <strong><xsl:value-of select="count(s:sitemap)"/></strong> sitemap(s).</p>
    <div class="card"><div class="scroll">
      <table>
        <thead><tr><th class="num">#</th><th>Sitemap</th><th>Last modified</th></tr></thead>
        <tbody>
          <xsl:for-each select="s:sitemap">
            <tr>
              <td class="num"><xsl:value-of select="position()"/></td>
              <td class="url"><a href="{s:loc}"><xsl:value-of select="s:loc"/></a></td>
              <td><xsl:value-of select="substring(s:lastmod,1,10)"/></td>
            </tr>
          </xsl:for-each>
        </tbody>
      </table>
    </div></div>
  </xsl:template>

  <!-- URL set: the actual page/product/post URLs -->
  <xsl:template match="s:urlset">
    <p class="count">This sitemap contains
      <strong><xsl:value-of select="count(s:url)"/></strong> URL(s).</p>
    <div class="card"><div class="scroll">
      <table>
        <thead><tr>
          <th class="num">#</th><th>URL</th><th class="num">Images</th>
          <th>Priority</th><th>Change freq.</th><th>Last modified</th>
        </tr></thead>
        <tbody>
          <xsl:for-each select="s:url">
            <tr>
              <td class="num"><xsl:value-of select="position()"/></td>
              <td class="url"><a href="{s:loc}"><xsl:value-of select="s:loc"/></a></td>
              <td class="num"><xsl:value-of select="count(image:image)"/></td>
              <td><xsl:value-of select="s:priority"/></td>
              <td><xsl:value-of select="s:changefreq"/></td>
              <td><xsl:value-of select="substring(s:lastmod,1,10)"/></td>
            </tr>
          </xsl:for-each>
        </tbody>
      </table>
    </div></div>
  </xsl:template>
</xsl:stylesheet>
`

export function GET() {
  return new Response(XSL, {
    headers: {
      'Content-Type': 'text/xsl; charset=utf-8',
      'Cache-Control': 'public, max-age=86400, s-maxage=86400',
    },
  })
}
